version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio_thesis
    restart: unless-stopped
    ports:
      - "9222:9000"
      - "9333:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - /data/minio2:/data
    command: server /data --console-address ":9001"